version: '3.9'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - GOOGLE_AI_API_KEY=[ここにAPIキーを入力]
    ports:
      - 8080:8080
    networks:
      - elk
    depends_on:
      - elasticsearch
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: web
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - 3000:3000
    networks:
      - elk
networks:
  elk:
    driver: bridge